### ISSUE TITLE
build fails in Openshift - missing nsp?

### ISSUE THREAD

**Issue by banderle-incomm** [stianst/misc#2]
Was following the "how-to" - that I truly appreciate from    https://www.keycloak.org/2018/05/keycloak-on-openshift.html
When building the Node.js "service" application.

Running this on minishift 1.33 with this result:

Cloning "https://github.com/stianst/misc.git " ...
	Commit:	38ba9d4d58b9531412c356c8e5d28b6bff8d0249 (Fixes)
	Author:	stianst <stianst@gmail.com>
	Date:	Thu Jun 14 21:38:32 2018 +0200
Using 172.30.1.1:5000/openshift/nodejs@sha256:3cc041334eef8d5853078a0190e46a2998a70ad98320db512968f1de0561705e as the s2i builder image
tar: scripts: time stamp 2019-04-25 20:15:22 is 0.176324332 s in the future
tar: src/app.js: time stamp 2019-04-25 20:15:22 is 0.175708996 s in the future
tar: src/keycloak.json: time stamp 2019-04-25 20:15:22 is 0.175546314 s in the future
tar: src/package-lock.json: time stamp 2019-04-25 20:15:22 is 0.169620568 s in the future
tar: src/package.json: time stamp 2019-04-25 20:15:22 is 0.169397097 s in the future
tar: src: time stamp 2019-04-25 20:15:22 is 0.169315663 s in the future
---> Installing application source
---> Building your Node application from source
Current git config
url.https://github.com.insteadof=git@github.com: 
url.https://.insteadof=ssh:// 
url.https://github.com.insteadof=ssh://git@github.com 
---> Installing dependencies
---> Using 'npm install -s --only=production'
**sh: nsp: command not found**
error: build error: non-zero (13) exit code from 172.30.1.1:5000/openshift/nodejs@sha256:3cc041334eef8d5853078a0190e46a2998a70ad98320db512968f1de0561705e

**Comment by stianst** [comment]
Should be fixed with this: https://github.com/stianst/misc/pull/1

**Comment by banderle-incomm** [comment]
Sorry - now there is new unhappiness - shall I open a new issue?

build failure

Using 172.30.1.1:5000/openshift/nodejs@sha256:3cc041334eef8d5853078a0190e46a2998a70ad98320db512968f1de0561705e as the s2i builder image
---> Installing application source
---> Building your Node application from source
Current git config
url.https://github.com.insteadof=git@github.com: 
url.https://.insteadof=ssh:// 
url.https://github.com.insteadof=ssh://git@github.com 
---> Installing dependencies
---> Using 'npm install -s --only=production'
=== npm audit security report ===
# Run  npm install --save-dev coveralls@3.0.3  to resolve 7 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change
Moderate        Prototype Pollution
Package         hoek
Dependency of   coveralls [dev]
Path            coveralls > request > hawk > boom > hoek
More info       https://nodesecurity.io/advisories/566 
Moderate        Prototype Pollution
Package         hoek
Dependency of   coveralls [dev]
Path            coveralls > request > hawk > cryptiles > boom > hoek
More info       https://nodesecurity.io/advisories/566 
Moderate        Prototype Pollution
Package         hoek
Dependency of   coveralls [dev]
Path            coveralls > request > hawk > hoek
More info       https://nodesecurity.io/advisories/566 
Moderate        Prototype Pollution
Package         hoek
Dependency of   coveralls [dev]
Path            coveralls > request > hawk > sntp > hoek
More info       https://nodesecurity.io/advisories/566 
Moderate        Memory Exposure
Package         tunnel-agent
Dependency of   coveralls [dev]
Path            coveralls > request > tunnel-agent
More info       https://nodesecurity.io/advisories/598 
Moderate        Denial of Service
Package         js-yaml
Dependency of   coveralls [dev]
Path            coveralls > js-yaml
More info       https://nodesecurity.io/advisories/788 
High            Code Injection
Package         js-yaml
Dependency of   coveralls [dev]
Path            coveralls > js-yaml
More info       https://nodesecurity.io/advisories/813 
# Run  npm install --save-dev eslint@5.16.0  to resolve 4 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change
Moderate        Denial of Service
Package         js-yaml
Dependency of   eslint [dev]
Path            eslint > js-yaml
More info       https://nodesecurity.io/advisories/788 
Moderate        Prototype Pollution
Package         lodash
Dependency of   eslint [dev]
Path            eslint > inquirer > lodash
More info       https://nodesecurity.io/advisories/782 
Moderate        Prototype Pollution
Package         lodash
Dependency of   eslint [dev]
Path            eslint > lodash
More info       https://nodesecurity.io/advisories/782 
Moderate        Prototype Pollution
Package         lodash
Dependency of   eslint [dev]
Path            eslint > table > lodash
More info       https://nodesecurity.io/advisories/782 
# Run  npm install --save-dev jshint@2.10.2  to resolve 2 vulnerabilities
Moderate        Prototype Pollution
Package         lodash
Dependency of   jshint [dev]
Path            jshint > lodash
More info       https://nodesecurity.io/advisories/782 
Low             Prototype Pollution
Package         lodash
Dependency of   jshint [dev]
Path            jshint > lodash
More info       https://nodesecurity.io/advisories/577 
# Run  npm update request --depth 2  to resolve 5 vulnerabilities
Moderate        Prototype Pollution
Package         hoek
Dependency of   keycloak-client-registration [dev]
Path            keycloak-client-registration > request > hawk > cryptiles >
boom > hoek
More info       https://nodesecurity.io/advisories/566 
Moderate        Prototype Pollution
Package         hoek
Dependency of   keycloak-client-registration [dev]
Path            keycloak-client-registration > request > hawk > hoek
More info       https://nodesecurity.io/advisories/566 
Moderate        Prototype Pollution
Package         hoek
Dependency of   keycloak-client-registration [dev]
Path            keycloak-client-registration > request > hawk > sntp > hoek
More info       https://nodesecurity.io/advisories/566 
Moderate        Prototype Pollution
Package         hoek
Dependency of   keycloak-client-registration [dev]
Path            keycloak-client-registration > request > hawk > boom > hoek
More info       https://nodesecurity.io/advisories/566 
Moderate        Memory Exposure
Package         tunnel-agent
Dependency of   keycloak-client-registration [dev]
Path            keycloak-client-registration > request > tunnel-agent
More info       https://nodesecurity.io/advisories/598 
# Run  npm update js-yaml --depth 2  to resolve 3 vulnerabilities
Moderate        Denial of Service
Package         js-yaml
Dependency of   istanbul [dev]
Path            istanbul > js-yaml
More info       https://nodesecurity.io/advisories/788 
High            Code Injection
Package         js-yaml
Dependency of   eslint [dev]
Path            eslint > js-yaml
More info       https://nodesecurity.io/advisories/813 
High            Code Injection
Package         js-yaml
Dependency of   istanbul [dev]
Path            istanbul > js-yaml
More info       https://nodesecurity.io/advisories/813 
# Run  npm update handlebars --depth 2  to resolve 1 vulnerability
High            Prototype Pollution
Package         handlebars
Dependency of   istanbul [dev]
Path            istanbul > handlebars
More info       https://nodesecurity.io/advisories/755 
Manual Review
Some vulnerabilities require your attention to resolve
Visit https://go.npm.me/audit-guide  for additional guidance
Moderate        Regular Expression Denial of Service
Package         marked
Patched in      >=0.6.2
Dependency of   jsdoc [dev]
Path            jsdoc > marked
More info       https://nodesecurity.io/advisories/812 
found 23 vulnerabilities (1 low, 18 moderate, 4 high) in 1012 scanned packages
run `npm audit fix` to fix 11 of them.
11 vulnerabilities require semver-major dependency updates.
1 vulnerability requires manual review. See the full report for details.
error: build error: non-zero (13) exit code from 172.30.1.1:5000/openshift/nodejs@sha256:3cc041334eef8d5853078a0190e46a2998a70ad98320db512968f1de0561705e

**Comment by banderle-incomm** [comment]
Ugh, sorry for the markdown ugliness.
